#!/usr/bin/env bash
#             __ _                           _
#  _ __ ___  / _(_)      _ __   ___  _ __ __| |_   ___ __  _ __
# | '__/ _ \| |_| |_____| '_ \ / _ \| '__/ _` \ \ / / '_ \| '_ \
# | | | (_) |  _| |_____| | | | (_) | | | (_| |\ V /| |_) | | | |
# |_|  \___/|_| |_|     |_| |_|\___/|_|  \__,_| \_/ | .__/|_| |_|
#                                                   |_|

# exit when any command fails
set -e

echoexit() {
    # Print to stderr and exit
    printf "%s\n" "$@" 1>&2
    exit 1
}

# Checking dependencies:
type nordvpn >/dev/null || echoexit "'nordvpn' not found."
type rofi >/dev/null || echoexit "'rofi' not found."

clean_output() {
    tr -s '\t' '\n' | sed 's/\.*\|\-*\|[[:space:]]//g'
}

menu() {
    # Menu command, should read from stdin and write to stdout.
    local stdin
    local line_count
    stdin="$(cat)"
    line_count="$(printf "%s" "$stdin" | wc -l)"

    if [ "$line_count" -lt 5 ]; then
        printf "%s" "$stdin" | rofi -dmenu -i -p "NordVPN" -no-custom -l "$((line_count + 1))"
    else
        printf "%s" "$stdin" | rofi -dmenu -i -p "NordVPN" -no-custom
    fi
}

usage() {
    printf "Dynamic menu interface for nordvpn.

Usage:
  rofi-nordvpn [-h] [-s]
    -h                                 Display this help message.
    -s                                 Display current vpn status, useful for status bars.
"
}

# Initial menu.
init_menu() {
    local choices
    choices="Connect\nDisconnect\nStatus\nSettings"
    printf "%b" "$choices" | menu
}

# nordvpn connect menu.
connect() {
    local choices
    choices="Fastest\nCountries\nCities\nGroups"
    printf "%b" "$choices" | menu
}

# Country selection menu.
countries() {
    country=`(echo "Fastest"; (nordvpn countries | clean_output)) | menu`
 echo "${country}"
}

connect_to_country() {
    local country
    country="$(countries)"
    if [[ "${country}" == "Fastest" ]]; then
        nordvpn connect
    else
        [ -n "${country}" ] && nordvpn connect "$country"
    fi
}

# City selection menu.
# Arg :
#   $1: a country
cities() {
    city=`(echo "Fastest"; (nordvpn cities "$1" | clean_output)) | menu`
    echo "${city}"
}

connect_to_city() {
    country="$(countries)"
    if [[ "${country}" == "Fastest" ]]; then
        nordvpn connect
    else
        [ -n "$country" ] && city="$(cities "$country")"
        if [[ "${city}" == "Fastest" ]]; then
            [ -n "${country}" ] && nordvpn connect "$country"
        else
            [ -n "$city" ] && nordvpn connect "$country" "$city"
        fi
    fi
}
# Print the vpn status, for status bars.
status() {
    local status
    status="$(nordvpn status | tr -d '\r -')"
    if [ -n "${status##*Connected*}" ]; then
        printf "Off"
    else
        printf "%s" "$(printf "%s" "$status" | grep "City" | cut -d ":" -f 2)"
    fi
}

# Show vpn status menu.
vpn_status() {
    local choices
    choices="$(nordvpn status | tr -d '\r-' | sed 's/^ *//')"
    printf "%s" "$choices" | menu
}

# Show vpn settings.
settings() {
    local choices
    choices="$(nordvpn settings | tr -d '\r-' | sed 's/^ *//')"
    printf "%s" "$choices" | menu
}

# Parse options to the `rofi-nordvpn` command
while getopts ":hs" opt; do
    case ${opt} in
    h)
        usage
        exit 0
        ;;
    s)
        status
        exit 0
        ;;
    \?)
        printf "Invalid Option: -%s\n" "$OPTARG" 1>&2
        usage
        exit 1
        ;;
    esac
done


case "$(init_menu)" in
    "Connect")
          case $(connect) in
              "Fastest")
                  nordvpn connect
                  ;;
              "Countries")
                  connect_to_country
                  ;;
              "Cities")
                  connect_to_city
                  ;;
              "Groups")
                  nordvpn connect p2p
                  ;;
              *) ;;
          esac
        ;;
    "Disconnect")
        nordvpn disconnect
        ;;
    "Status")
        vpn_status
        ;;
    "Settings")
        settings
        ;;
    *) ;;
esac
